language: php

# PHP 7.1 crashes when collecting coverage
php:
  - 7.2
  - 7.3
  - 7.4

cache:
  directories:
    - ./vendor
    - $HOME/.composer/cache

env:
  - LARAVEL_VERSION=5.6.* TESTBENCH_VERSION=3.6.*
  - LARAVEL_VERSION=5.7.* TESTBENCH_VERSION=3.7.*
  - LARAVEL_VERSION=5.8.* TESTBENCH_VERSION=3.8.*
  - LARAVEL_VERSION=^6.0 TESTBENCH_VERSION=^4.0

before_script:
  - composer self-update
  - composer require "laravel/framework:${LARAVEL_VERSION}" "orchestra/testbench:${TESTBENCH_VERSION}" --no-update
  - if [ "$PHPUNIT_VERSION" != "" ]; then composer require "phpunit/phpunit:${PHPUNIT_VERSION}" --no-update; fi;
  - composer update
  - mkdir -p build/logs

script:
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_success:
  - |
    travis_retry wget https://scrutinizer-ci.com/ocular.phar
    travis_retry php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
